/*
 * This Java source file was generated by the Gradle 'init' task.
 */

Import java.awt.image.BufferedImage;

public class App {


    public static void main(String[] args) {
        Bitmap transformImage  = new Bitmap(input, output, pathtransform, name);
    }
}
